### ISSUE TITLE
Fix Split on Undefined Issue

### ISSUE THREAD

**Issue by vkoves** [IndigoBox/Scroll-Stop#1]
If you add Scroll Stop but don't add any sites, it creates a console error indicating that it cannot split on undefined. This in `siteBlocked()` here:
```
var siteArray = siteURLs.split(",");
```

This can be easily fixed by making `siteBlocked()` return false if `siteURLs` is null or empty, as no site can be blocked if there are no urls.

**Comment by AcademyInPeril** [comment]
@vkoves, can you test this most recent commit? It's not creating any console errors for me and everything appears to be working properly, but I wasn't able to recreate the original issue and want to make sure it's been dealt with on your end now.

**Comment by vkoves** [comment]
Verified that this issue is resolved on `master`. Sorry for the delay @AcademyInPeril
