### ISSUE TITLE
Functionality breaks on certain sites with complex features

### ISSUE THREAD

**Issue by SorenSpicknall** [IndigoBox/Scroll-Stop#7]
The current version of Scroll Stop appears to not work on sites like Google News, Google Drive, Outlook, and others that have complex features. Most sites found to break functionality have a sidebar, which in many cases is itself scrollable. Each such site also has a floating header. It is unclear whether either of these features are a contributing factor, but my money's on the former as a cause. In addition to sites meeting those criteria, some parallax scrolling sites (like the homepages of Tumblr) exhibit this behavior as well.

This should likely be remedied before the launch of the next update, if at all possible. However, it might be hard to find a universal solution.

**Comment by rjaltman** [comment]
Just to make sure, the pages are saved with blocking enabled, but the scrolling and positioning itself is the problem, correct?

**Comment by AcademyInPeril** [comment]
That is correct. Opening the status dialog on each of these malfunctioning pages indicates that Scroll Stop "knows" that it should be working there, but it simply doesn't do anything beyond that.
